name: Deploy produto-dev Terraform Workspace
"on":
    push:
        branches:
            - main
        paths:
            - produto/deployments/terragrunt/us-east1/dev/topic/**
            - produto/deployments/terragrunt/us-east1/dev/topic/produto/deployments/terragrunt/us-east1/dev/topic
    pull_request:
        branches:
            - main
        paths:
            - produto/deployments/terragrunt/us-east1/dev/topic/**
            - produto/deployments/terragrunt/us-east1/dev/topic/produto/deployments/terragrunt/us-east1/dev/topic
    workflow_dispatch:
        inputs:
            apply:
                description: Should apply Terraform changes?
                type: boolean
                default: false
jobs:
    deploy:
        name: Deploy Terraform Workspace
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        defaults:
            run:
                working-directory: produto/deployments/terragrunt/us-east1/dev/topic
        env:
            FIREFLY_ACCESS_KEY: ${{ secrets.FIREFLY_ACCESS_KEY }}
            FIREFLY_SECRET_KEY: ${{ secrets.FIREFLY_SECRET_KEY }}
            TF_VAR_managedBy: firefly
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set deployment parameters
              id: set-params
              run: |-
                if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                  echo "apply=${{ github.event.inputs.apply }}" >> $GITHUB_OUTPUT
                elif [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
                  echo "apply=true" >> $GITHUB_OUTPUT
                else
                  echo "apply=false" >> $GITHUB_OUTPUT
                fi
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.12.1
                terraform_wrapper: false
            - name: Initialize Terraform
              id: init
              run: |-
                terraform init >& init.log
                terraform workspace new dev || terraform workspace select dev
              continue-on-error: true
            - name: Terraform Plan
              id: plan
              if: steps.init.outcome == 'success'
              run: terraform plan -json -var-file=produto/deployments/terragrunt/us-east1/dev/topic/ -out=tf.plan > plan_log.jsonl && terraform show -json tf.plan > plan_output.json && terraform show tf.plan > plan_output_raw.log
              continue-on-error: true
            - name: Firefly Post Plan
              uses: gofireflyio/fireflyci@v0.5.101
              with:
                command: post-plan
                context: produto/deployments/terragrunt/us-east1/dev/topic
                init-log-file: init.log
                plan-json-log-file: plan_log.jsonl
                plan-output-file: plan_output.json
                plan-raw-log-file: plan_output_raw.log
                workspace: produto-dev
            - name: Terraform Apply
              if: steps.set-params.outputs.apply == 'true' && steps.plan.outcome == 'success'
              run: terraform apply -auto-approve -var-file=produto/deployments/terragrunt/us-east1/dev/topic/ -json > apply_log.jsonl
              continue-on-error: true
            - name: Firefly Post Apply
              if: steps.set-params.outputs.apply == 'true' && steps.plan.outcome == 'success'
              uses: gofireflyio/fireflyci@v0.5.101
              with:
                apply-log-file: apply_log.jsonl
                command: post-apply
                context: produto/deployments/terragrunt/us-east1/dev/topic
                workspace: produto-dev
              continue-on-error: true
